# Generated by Django 5.2.17 on 2026-08-05 16:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('memory', '0001_initial'),
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyResearchHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(blank=True, max_length=16)),
                ('company_name', models.CharField(max_length=255)),
                ('query', models.TextField()),
                ('response_summary', models.TextField()),
                ('sources', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'company_research_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('price_move', 'Price Move'), ('earnings', 'Earnings'), ('news', 'News'), ('sec_filing', 'SEC Filing')], max_length=16)),
                ('trigger_data', models.JSONField(blank=True, default=dict)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('notified', models.BooleanField(default=False)),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='market_alerts', to='notifications.notificationlog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_alerts', to=settings.AUTH_USER_MODEL)),
                ('watchlist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='memory.watchlist')),
            ],
            options={
                'db_table': 'market_alerts',
                'ordering': ['-triggered_at'],
            },
        ),
    ]
