# Generated by Django 5.2.17 on 2026-08-07 06:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SheetSyncState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mode', models.CharField(choices=[('oauth', 'OAuth'), ('demo', 'Local demo')], default='demo', max_length=16)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('failed', 'Failed')], default='idle', max_length=16)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.CharField(blank=True, max_length=512)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sheet_sync_state', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sheet_sync_states',
            },
        ),
        migrations.CreateModel(
            name='SheetWorkbook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('spreadsheet_id', models.CharField(db_index=True, max_length=128)),
                ('title', models.CharField(max_length=512)),
                ('modified_time', models.DateTimeField(blank=True, null=True)),
                ('sheet_names', models.JSONField(blank=True, default=list)),
                ('content_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('detected', models.JSONField(blank=True, default=dict)),
                ('is_trashed', models.BooleanField(default=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheet_workbooks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sheet_workbooks',
                'indexes': [models.Index(fields=['user', 'is_trashed', 'title'], name='sheet_workb_user_id_237159_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'spreadsheet_id'), name='uniq_user_spreadsheet')],
            },
        ),
    ]
