# Generated by Django 5.2.17 on 2026-08-05 16:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_briefing_time', models.TimeField(blank=True, null=True)),
                ('briefing_timezone', models.CharField(default='UTC', max_length=64)),
                ('insight_types', models.JSONField(blank=True, default=list)),
                ('response_style', models.CharField(choices=[('concise', 'Concise'), ('detailed', 'Detailed')], default='concise', max_length=16)),
                ('sectors_of_interest', models.JSONField(blank=True, default=list)),
                ('markets_of_interest', models.JSONField(blank=True, default=list)),
                ('additional_verticals', models.JSONField(blank=True, default=list)),
                ('language', models.CharField(default='en', max_length=16)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_preferences',
            },
        ),
        migrations.CreateModel(
            name='AssistantMemory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('memory_type', models.CharField(choices=[('fact', 'Fact'), ('preference', 'Preference'), ('task', 'Task'), ('context', 'Context')], max_length=16)),
                ('key', models.CharField(db_index=True, max_length=128)),
                ('value', models.JSONField()),
                ('source', models.CharField(choices=[('onboarding', 'Onboarding'), ('conversation', 'Conversation'), ('inferred', 'Inferred')], max_length=16)),
                ('confidence', models.FloatField(default=1.0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assistant_memory',
                'indexes': [models.Index(fields=['user', 'key'], name='assistant_m_user_id_7a6a02_idx')],
            },
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symbol', models.CharField(max_length=16)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('alert_on_news', models.BooleanField(default=True)),
                ('alert_on_sec_filing', models.BooleanField(default=True)),
                ('alert_on_price_move_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'watchlist',
                'constraints': [models.UniqueConstraint(fields=('user', 'symbol'), name='uniq_user_watchlist_symbol')],
            },
        ),
    ]
