# Generated by Django 5.2.17 on 2026-08-05 16:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('telegram_upload', 'Telegram Upload'), ('drive', 'Google Drive'), ('sec_edgar', 'SEC EDGAR')], max_length=32)),
                ('title', models.CharField(max_length=512)),
                ('file', models.FileField(blank=True, upload_to='documents/%Y/%m/')),
                ('mime_type', models.CharField(blank=True, max_length=128)),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('extracted_text', models.TextField(blank=True)),
                ('gemini_file_uri', models.CharField(blank=True, max_length=512)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'financial_documents',
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_index', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='documents.financialdocument')),
            ],
            options={
                'db_table': 'document_chunks',
                'ordering': ['chunk_index'],
                'constraints': [models.UniqueConstraint(fields=('document', 'chunk_index'), name='uniq_document_chunk_index')],
            },
        ),
    ]
