# Generated by Django 5.2.17 on 2026-08-06 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_milestone5_document_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='documentchunk',
            new_name='document_ch_documen_babbe5_idx',
            old_name='document_ch_documen_page_idx',
        ),
        migrations.RenameIndex(
            model_name='financialdocument',
            new_name='financial_d_user_id_e7c4d3_idx',
            old_name='financial_d_user_id_proc_idx',
        ),
        migrations.RenameIndex(
            model_name='financialdocument',
            new_name='financial_d_user_id_b3a21c_idx',
            old_name='financial_d_user_id_hash_idx',
        ),
    ]
