# Generated by Django 5.2.17 on 2026-08-06 13:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0003_milestone6_drive'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriveSyncState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mode', models.CharField(choices=[('oauth', 'OAuth'), ('demo', 'Local demo')], default='demo', max_length=16)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('failed', 'Failed')], default='idle', max_length=16)),
                ('page_token', models.CharField(blank=True, max_length=512)),
                ('last_full_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_incremental_sync_at', models.DateTimeField(blank=True, null=True)),
                ('selected_folder_ids', models.JSONField(blank=True, default=list)),
                ('error_message', models.CharField(blank=True, max_length=512)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='drive_sync_state', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'drive_sync_states',
            },
        ),
        migrations.CreateModel(
            name='DriveFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drive_file_id', models.CharField(db_index=True, max_length=128)),
                ('name', models.CharField(max_length=512)),
                ('mime_type', models.CharField(blank=True, max_length=256)),
                ('modified_time', models.DateTimeField(blank=True, null=True)),
                ('md5_checksum', models.CharField(blank=True, max_length=64)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('parents', models.JSONField(blank=True, default=list)),
                ('web_view_link', models.CharField(blank=True, max_length=1024)),
                ('is_folder', models.BooleanField(default=False)),
                ('is_trashed', models.BooleanField(default=False)),
                ('is_supported', models.BooleanField(default=True)),
                ('metadata_only', models.BooleanField(default=False)),
                ('content_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drive_origins', to='documents.financialdocument')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drive_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'drive_files',
                'indexes': [models.Index(fields=['user', 'is_trashed', 'name'], name='drive_files_user_id_0fe168_idx'), models.Index(fields=['user', 'modified_time'], name='drive_files_user_id_34628f_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'drive_file_id'), name='uniq_user_drive_file')],
            },
        ),
    ]
