# Generated by Django 5.2.17 on 2026-08-05 16:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('context_summary', models.TextField(blank=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'conversations',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System'), ('tool', 'Tool')], max_length=16)),
                ('content', models.TextField()),
                ('content_type', models.CharField(choices=[('text', 'Text'), ('voice_transcript', 'Voice Transcript'), ('image_description', 'Image Description'), ('document_ref', 'Document Reference')], default='text', max_length=32)),
                ('telegram_message_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='conversation.conversation')),
            ],
            options={
                'db_table': 'messages',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['conversation', 'created_at'], name='messages_convers_3ebb41_idx'), models.Index(fields=['conversation', 'is_archived'], name='messages_convers_421b82_idx')],
            },
        ),
    ]
