# Generated by Django 5.2.17 on 2026-08-05 16:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_type', models.CharField(choices=[('daily_briefing', 'Daily Briefing'), ('evening_summary', 'Evening Summary'), ('watchlist_scan', 'Watchlist Scan'), ('earnings_reminder', 'Earnings Reminder'), ('token_refresh', 'Token Refresh')], max_length=32)),
                ('cron_expression', models.CharField(blank=True, max_length=64)),
                ('run_at', models.DateTimeField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scheduled_tasks',
            },
        ),
    ]
